import { useEffect, useRef, useState } from "react";
import { json, request } from "../../api.js";

export function SqlEditor({ diagramId, readOnly = false, onApplied, diagramTitle, drawerMode = "partial", onDrawerModeChange }) {
  const [sql, setSql] = useState(""), [result, setResult] = useState(null), [busy, setBusy] = useState(false), [permission, setPermission] = useState(readOnly ? "viewer" : "editor");
  const setDrawerMode = onDrawerModeChange || (() => {}), gutterRef = useRef(null);
  useEffect(() => { request(`/diagrams/${diagramId}/sql`).then((data) => setSql(data.sql)).catch((error) => setResult({ errors: [{ message: error.message }] })); }, [diagramId]);
  useEffect(() => { setPermission(readOnly ? "viewer" : "editor"); }, [readOnly]);
  const viewer = readOnly || permission === "viewer";
  async function validate() { setBusy(true); try { setResult(await request(`/diagrams/${diagramId}/sql/parse`, json("POST", { sql }))); } catch (error) { setResult({ errors: [{ message: error.message }] }); } finally { setBusy(false); } }
  async function apply() { if (viewer || !window.confirm("Aplicar este DDL reemplazará el modelo de clases del lienzo. ¿Continuar?")) return; setBusy(true); try { const response = await request(`/diagrams/${diagramId}/sql/apply`, json("PUT", { sql })); setResult(response); if (response.valid) onApplied(response.diagram); } catch (error) { setResult({ errors: [{ message: error.message }] }); } finally { setBusy(false); } }
  const messages = (key) => (result?.[key] || []).map((item, index) => <li key={`${key}-${index}`}>{item.line ? `Línea ${item.line}, columna ${item.column}: ` : ""}{item.message || String(item)}</li>);
  const lineCount = Math.max(1, sql.split("\n").length), syncGutter = (event) => { if (gutterRef.current) gutterRef.current.scrollTop = event.currentTarget.scrollTop; };
  return <aside className={`sql-drawer sql-drawer-${drawerMode}`} aria-label="Editor SQL"><div className="sql-drawer-bar"><div><p className="eyebrow">DDL SEGURO · SIN EJECUCIÓN</p><strong>SQL Editor</strong><span className="sql-drawer-state">{drawerMode === "partial" ? "Vista parcial" : "Vista expandida"}</span></div><div className="sql-drawer-controls"><button type="button" className="ghost" onClick={() => setDrawerMode(drawerMode === "partial" ? "expanded" : "partial")} aria-label={drawerMode === "expanded" ? "Reducir editor SQL" : "Expandir editor SQL"}>{drawerMode === "expanded" ? "⌄ Reducir" : "⌃ Expandir"}</button></div></div><div className="sql-workspace"><section className="sql-shell" aria-labelledby="sql-title"><div className="sql-heading"><div><p className="eyebrow">DDL SEGURO · SIN EJECUCIÓN</p><h1 id="sql-title">SQL Editor</h1><p className="muted">{diagramTitle || "Diagrama"} · Edite PostgreSQL DDL y conviértalo en UML. El servidor nunca ejecuta este SQL.</p></div></div><div className="sql-editor"><div ref={gutterRef} className="sql-gutter" aria-hidden="true">{Array.from({ length: lineCount }, (_, index) => <span key={index}>{index + 1}</span>)}</div><textarea className="sql-textarea" value={sql} onChange={(event) => setSql(event.target.value)} onScroll={syncGutter} spellCheck="false" aria-label="SQL DDL" /></div>{result && <div className="sql-feedback">{result.errors?.length > 0 && <div className="sql-errors"><b>Errores</b><ul>{messages("errors")}</ul></div>}{result.warnings?.length > 0 && <div className="sql-warnings"><b>Advertencias</b><ul>{messages("warnings")}</ul></div>}{result.valid && <p className="notice">DDL válido: {result.diagram?.classes?.length || 0} clases y {result.diagram?.relations?.length || 0} relaciones en la vista previa.</p>}</div>}<div className="sql-actions"><button className="ghost" type="button" onClick={() => request(`/diagrams/${diagramId}/sql`).then((data) => { setSql(data.sql); setResult(null); })}>Generar desde UML</button><button type="button" onClick={validate} disabled={busy}>Validar / Vista previa</button>{!viewer && <button type="button" onClick={apply} disabled={busy || !result?.valid}>Aplicar al UML</button>}</div>{viewer && <small className="field-hint">Viewer: puede generar y validar, pero no aplicar cambios.</small>}</section></div></aside>;
}
