import { useEffect, useState } from "react";
import { ATTRIBUTE_TYPES, METHOD_TYPES, TYPE_LABELS } from "./inspector.constants.js";

function InspectorClose({ onClose }) { return <button type="button" className="inspector-close ghost" onClick={onClose}>Cerrar</button>; }
export function ClassInspector({ readOnly, selected, onPatch, onDelete, onAdd, onItemPatch, onItemDelete, onClose }) {
  const [nameDraft, setNameDraft] = useState(""), [itemDrafts, setItemDrafts] = useState({});
  useEffect(() => { setNameDraft(selected?.name || ""); setItemDrafts(selected ? Object.fromEntries([...selected.attributes.map((item) => [`attributes:${item.id}`, { ...item, custom: !ATTRIBUTE_TYPES.includes(item.type) }]), ...selected.methods.map((item) => [`methods:${item.id}`, { ...item, custom: !METHOD_TYPES.includes(item.type) }])]) : {}); }, [selected?.id, selected?.name, selected?.attributes, selected?.methods]);
  if (!selected) return <aside className="inspector"><InspectorClose onClose={onClose} /><p className="eyebrow">INSPECTOR</p><div className="empty-inspector"><b>Seleccionar un elemento</b><span>Elija una clase o relación en la pizarra para editarla.</span></div></aside>;
  if (readOnly) return <aside className="inspector"><InspectorClose onClose={onClose} /><p className="eyebrow">MODO LECTURA</p><div className="empty-inspector"><b>Puede consultar esta pizarra</b><span>Su permiso Viewer no permite modificar clases, detalles ni relaciones.</span></div></aside>;
  const saveName = () => { if (nameDraft !== selected.name) onPatch({ name: nameDraft }); };
  const update = (kind, item, field, value) => setItemDrafts((current) => ({ ...current, [`${kind}:${item.id}`]: { ...(current[`${kind}:${item.id}`] || item), [field]: value } }));
  const saveItem = (kind, item) => { const draft = itemDrafts[`${kind}:${item.id}`] || item, patch = {}; if (draft.name !== item.name) patch.name = draft.name; if (draft.type !== item.type) patch.type = draft.type; if (Object.keys(patch).length) onItemPatch(kind, item.id, patch); };
  const editor = (kind, item) => { const types = kind === "attributes" ? ATTRIBUTE_TYPES : METHOD_TYPES, draft = itemDrafts[`${kind}:${item.id}`] || item, custom = draft.custom || !types.includes(draft.type), noun = kind === "attributes" ? "atributo" : "método"; return <div className="detail" key={item.id}><input aria-label={`Nombre de ${noun}`} value={draft.name} onChange={(e) => update(kind, item, "name", e.target.value)} onBlur={() => saveItem(kind, item)} onKeyDown={(e) => e.key === "Enter" && e.currentTarget.blur()} /><select aria-label={kind === "attributes" ? "Tipo de atributo" : "Tipo de retorno"} value={custom ? "Custom" : draft.type} onChange={(e) => { update(kind, item, "custom", e.target.value === "Custom"); if (e.target.value !== "Custom") update(kind, item, "type", e.target.value); }} onBlur={() => saveItem(kind, item)}>{types.map((type) => <option key={type} value={type}>{TYPE_LABELS[type]}</option>)}<option value="Custom">Personalizado</option></select>{custom && <input aria-label={`Tipo personalizado de ${noun}`} placeholder="Tipo personalizado" value={draft.type} onChange={(e) => update(kind, item, "type", e.target.value)} onBlur={() => saveItem(kind, item)} />}<button className="mini danger" aria-label={`Eliminar ${noun}`} onClick={() => onItemDelete(kind, item.id)}>×</button></div>; };
  return <aside className="inspector"><InspectorClose onClose={onClose} /><p className="eyebrow">INSPECTOR DE CLASE</p><label>Nombre<input value={nameDraft} onChange={(e) => setNameDraft(e.target.value)} onBlur={saveName} onKeyDown={(e) => e.key === "Enter" && e.currentTarget.blur()} /></label><section className="inspector-group"><div className="section-title">Atributos <button className="mini" aria-label="Agregar atributo" onClick={() => onAdd("attributes")}>+</button></div><small className="field-hint">Tipo de atributo</small>{selected.attributes.map((a) => editor("attributes", a))}</section><section className="inspector-group"><div className="section-title">Métodos <button className="mini" aria-label="Agregar método" onClick={() => onAdd("methods")}>+</button></div><small className="field-hint">Tipo de retorno</small>{selected.methods.map((m) => editor("methods", m))}</section><button className="delete" onClick={onDelete}>Eliminar clase</button></aside>;
}
