import { useEffect, useState } from "react";
import { CUSTOM_MULTIPLICITY, ENDPOINT_LABELS, MULTIPLICITY_OPTIONS, RELATION_LABELS, RELATION_TYPES } from "./inspector.constants.js";

function InspectorClose({ onClose }) { return <button type="button" className="inspector-close ghost" onClick={onClose}>Cerrar</button>; }
const choice = (value) => MULTIPLICITY_OPTIONS.includes(value) ? value : CUSTOM_MULTIPLICITY;
export function RelationInspector({ readOnly, relation, diagram, onPatch, onDelete, onClose }) {
  const [drafts, setDrafts] = useState({ source: { value: "", choice: CUSTOM_MULTIPLICITY }, target: { value: "", choice: CUSTOM_MULTIPLICITY } });
  const [labelDraft, setLabelDraft] = useState("");
  useEffect(() => { const draft = (side) => { const value = relation?.[`${side}_multiplicity`] || ""; return { value, choice: choice(value) }; }; setDrafts({ source: draft("source"), target: draft("target") }); setLabelDraft(relation?.label || ""); }, [relation?.id]);
  const endpoint = (side) => { const info = relation?.[`${side}_endpoint_info`] || {}, className = info.class_name || info.class || relation?.[side === "source" ? "from" : "to"] || "Clase desconocida", type = info.type || "class", detailType = type === "attribute" ? `Atributo · ${info.data_type || "tipo desconocido"}` : type === "method" ? `Método · retorno ${info.return_type || "tipo desconocido"}` : "Clase", current = diagram?.classes?.find((item) => item.id === relation?.[`${side}_id`]); return { className: current?.name || className, name: info.name || className, detailType }; };
  const source = endpoint("source"), target = endpoint("target"), endpointView = <div className="relation-endpoints"><div><small>Origen</small><b>{source.className}</b><span>{source.name} · {source.detailType}</span></div><div><small>Destino</small><b>{target.className}</b><span>{target.name} · {target.detailType}</span></div></div>;
  if (readOnly) return <aside className="inspector"><InspectorClose onClose={onClose} /><p className="eyebrow">MODO LECTURA</p>{endpointView}<div className="empty-inspector"><b>Puede consultar esta relación</b><span>Su permiso Viewer no permite modificarla.</span></div></aside>;
  const setMultiplicity = (side, next) => setDrafts((current) => ({ ...current, [side]: { choice: next, value: next === CUSTOM_MULTIPLICITY ? current[side].value : next } }));
  const saveMultiplicity = (side) => { const field = `${side}_multiplicity`, value = drafts[side].value.trim(); if (value !== (relation[field] || "")) onPatch({ [field]: value || null }); };
  const saveLabel = () => { if (labelDraft !== (relation?.label || "")) onPatch({ label: labelDraft }); };
  const field = (side, label) => { const draft = drafts[side]; return <div className="multiplicity-field"><label>{label}<select aria-label={label} value={draft.choice} onChange={(e) => setMultiplicity(side, e.target.value)} onBlur={() => saveMultiplicity(side)}>{MULTIPLICITY_OPTIONS.map((value) => <option key={value} value={value}>{value}</option>)}<option value={CUSTOM_MULTIPLICITY}>Personalizada</option></select></label>{draft.choice === CUSTOM_MULTIPLICITY && <input aria-label={`${label} personalizada`} placeholder="Ej. 2..5" value={draft.value} onChange={(e) => setDrafts((current) => ({ ...current, [side]: { ...current[side], value: e.target.value } }))} onBlur={() => saveMultiplicity(side)} onKeyDown={(e) => e.key === "Enter" && e.currentTarget.blur()} />}</div>; };
  return <aside className="inspector"><InspectorClose onClose={onClose} /><p className="eyebrow">INSPECTOR DE RELACIÓN</p><label>Tipo<select value={relation.type} onChange={(e) => onPatch({ type: e.target.value })}>{RELATION_TYPES.map((x) => <option key={x} value={x}>{RELATION_LABELS[x]}</option>)}</select></label><label>Etiqueta<input value={labelDraft} onChange={(e) => setLabelDraft(e.target.value)} onBlur={saveLabel} onKeyDown={(e) => { if (e.key === "Enter") e.currentTarget.blur(); }} /></label><div className="detail relation-multiplicities">{field("source", "Multiplicidad de origen")}{field("target", "Multiplicidad de destino")}</div>{endpointView}<p className="muted">{relation.from} · {relation.source_endpoint_info?.name} → {relation.to} · {relation.target_endpoint_info?.name}</p><p className="endpoint-summary">{ENDPOINT_LABELS[relation.source_endpoint_info?.type] || relation.source_endpoint_info?.type} → {ENDPOINT_LABELS[relation.target_endpoint_info?.type] || relation.target_endpoint_info?.type}</p><button className="delete" onClick={onDelete}>Eliminar relación</button></aside>;
}
