import { useState } from "react";
import { CUSTOM_MULTIPLICITY, ENDPOINT_LABELS, RELATION_TYPES } from "./relation.constants.js";
import { directionalMultiplicityLabel, relationMultiplicityPayload, relationMultiplicityPreview } from "./multiplicity-direction.js";

function MultiplicityControl({ label, choice, value, onChoice, onValue }) { return <div className="multiplicity-field"><label>{label}<select aria-label={label} value={choice} onChange={(e) => onChoice(e.target.value)}><option value="1">1</option><option value="0..1">0..1</option><option value="*">*</option><option value="1..*">1..*</option><option value="0..*">0..*</option><option value={CUSTOM_MULTIPLICITY}>Personalizada</option></select></label>{choice === CUSTOM_MULTIPLICITY && <input aria-label={`${label} personalizada`} placeholder="Ej. 2..5" value={value} onChange={(e) => onValue(e.target.value)} />}</div>; }
export function RelationModal({ classes, initialSource, onCancel, onCreate }) {
  const [form, setForm] = useState({ source_id: initialSource || "", target_id: "", source_endpoint: "class", target_endpoint: "class", type: "association", source_multiplicity: "1", target_multiplicity: "*", source_multiplicity_choice: "1", target_multiplicity_choice: "*", label: "" }), [error, setError] = useState("");
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const setMultiplicityChoice = (side, choice) => { set(`${side}_multiplicity_choice`, choice); set(`${side}_multiplicity`, choice === CUSTOM_MULTIPLICITY ? "" : choice); };
  const endpointOptions = (id) => { const c = classes.find((x) => x.id === id); return c ? [{ value: "class", label: `${c.name} (${ENDPOINT_LABELS.class})` }, ...c.attributes.map((x) => ({ value: `attribute:${x.id}`, label: `${x.name} (${ENDPOINT_LABELS.attribute})` })), ...c.methods.map((x) => ({ value: `method:${x.id}`, label: `${x.name} (${ENDPOINT_LABELS.method})` }))] : []; };
  async function submit(e) { e.preventDefault(); if (!form.target_id) return setError("Elija una clase de destino."); const parse = (value) => value === "class" ? { type: "class", id: null } : { type: value.split(":")[0], id: value.split(":")[1] }; const source = parse(form.source_endpoint), target = parse(form.target_endpoint); try { await onCreate({ source_id: form.source_id, target_id: form.target_id, source_endpoint: source.id, target_endpoint: target.id, source_endpoint_type: source.type, target_endpoint_type: target.type, type: form.type, label: form.label || null, ...relationMultiplicityPayload(form.source_multiplicity, form.target_multiplicity) }); } catch (e) { setError(e.message); } }
  const selectClass = (side, label, empty = false) => <label>{label}<select value={form[`${side}_id`]} onChange={(e) => { set(`${side}_id`, e.target.value); set(`${side}_endpoint`, "class"); }}>{empty && <option value="">Elija el destino</option>}{classes.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>;
  const selectEndpoint = (side, label) => <label>{label}<select value={form[`${side}_endpoint`]} onChange={(e) => set(`${side}_endpoint`, e.target.value)}>{endpointOptions(form[`${side}_id`]).map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select></label>;
  const sourceName = classes.find((item) => item.id === form.source_id)?.name || "A";
  const targetName = classes.find((item) => item.id === form.target_id)?.name || "B";
  const selfRelation = form.source_id && form.source_id === form.target_id;
  const sourceLabel = directionalMultiplicityLabel(sourceName, targetName, "source", selfRelation);
  const targetLabel = directionalMultiplicityLabel(sourceName, targetName, "target", selfRelation);
  return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onCancel()}><form className="relation-modal" onSubmit={submit}><div className="modal-heading"><div><p className="eyebrow">NUEVA RELACIÓN</p><h2>Conectar extremos UML</h2><p className="muted">Podés conectar una clase consigo misma para modelar una relación recursiva.</p></div><button type="button" className="ghost" aria-label="Cerrar" onClick={onCancel}>×</button></div><div className="modal-grid">{selectClass("source", "Clase de origen")}{selectEndpoint("source", "Extremo de origen")}{selectClass("target", "Clase de destino", true)}{selectEndpoint("target", "Extremo de destino")}<label>Tipo de relación<select value={form.type} onChange={(e) => set("type", e.target.value)}>{RELATION_TYPES.map((x) => <option key={x} value={x}>{x}</option>)}</select></label><label>Etiqueta (opcional)<input value={form.label} onChange={(e) => set("label", e.target.value)} /></label><MultiplicityControl label={targetLabel} choice={form.target_multiplicity_choice} value={form.target_multiplicity} onChoice={(value) => setMultiplicityChoice("target", value)} onValue={(value) => set("target_multiplicity", value)} /><MultiplicityControl label={sourceLabel} choice={form.source_multiplicity_choice} value={form.source_multiplicity} onChoice={(value) => setMultiplicityChoice("source", value)} onValue={(value) => set("source_multiplicity", value)} /></div><p className="muted multiplicity-help">En UML, cada valor se muestra en el extremo opuesto de la dirección.</p><div className="multiplicity-preview" aria-live="polite"><span>Vista previa</span><strong>{relationMultiplicityPreview(sourceName, targetName, form.source_multiplicity, form.target_multiplicity)}</strong></div>{error && <p className="error">{error}</p>}<button type="submit">Crear relación</button></form></div>;
}
