from alembic import op

revision = "0005_diagram_members"
down_revision = "0004_user_roles"
branch_labels = None
depends_on = None

def upgrade():
    # This revision may be resumed after the table was created but before the
    # alembic_version row was committed. Keep every DDL operation resumable.
    op.execute("""
        CREATE TABLE IF NOT EXISTS diagram_members (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            diagram_id UUID NOT NULL,
            user_id INTEGER NOT NULL,
            role VARCHAR(20) NOT NULL DEFAULT 'viewer',
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("ALTER TABLE diagram_members ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY")
    op.execute("ALTER TABLE diagram_members ADD COLUMN IF NOT EXISTS diagram_id UUID")
    op.execute("ALTER TABLE diagram_members ADD COLUMN IF NOT EXISTS user_id INTEGER")
    op.execute("ALTER TABLE diagram_members ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'viewer'")
    op.execute("ALTER TABLE diagram_members ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE")
    op.execute("ALTER TABLE diagram_members ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")

    # Only repair missing values introduced by an interrupted/partial DDL.
    op.execute("UPDATE diagram_members SET role = 'viewer' WHERE role IS NULL")
    op.execute("UPDATE diagram_members SET active = TRUE WHERE active IS NULL")
    op.execute("UPDATE diagram_members SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("ALTER TABLE diagram_members ALTER COLUMN role SET DEFAULT 'viewer'")
    op.execute("ALTER TABLE diagram_members ALTER COLUMN active SET DEFAULT TRUE")
    op.execute("ALTER TABLE diagram_members ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP")
    op.execute("ALTER TABLE diagram_members ALTER COLUMN diagram_id SET NOT NULL")
    op.execute("ALTER TABLE diagram_members ALTER COLUMN user_id SET NOT NULL")
    op.execute("ALTER TABLE diagram_members ALTER COLUMN role SET NOT NULL")
    op.execute("ALTER TABLE diagram_members ALTER COLUMN active SET NOT NULL")
    op.execute("ALTER TABLE diagram_members ALTER COLUMN created_at SET NOT NULL")

    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'diagram_members'::regclass
                  AND conname = 'diagram_members_pkey'
            ) THEN
                ALTER TABLE diagram_members
                    ADD CONSTRAINT diagram_members_pkey PRIMARY KEY (id);
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'diagram_members'::regclass
                  AND conname = 'uq_diagram_member'
            ) THEN
                ALTER TABLE diagram_members
                    ADD CONSTRAINT uq_diagram_member UNIQUE (diagram_id, user_id);
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'diagram_members'::regclass
                  AND conname = 'ck_diagram_member_role'
            ) THEN
                ALTER TABLE diagram_members
                    ADD CONSTRAINT ck_diagram_member_role
                    CHECK (role IN ('editor', 'viewer'));
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'diagram_members'::regclass
                  AND contype = 'f'
                  AND lower(pg_get_constraintdef(oid)) LIKE
                      'foreign key (diagram_id) references diagrams(id) on delete cascade%'
            ) THEN
                ALTER TABLE diagram_members
                    ADD CONSTRAINT fk_diagram_members_diagram_id
                    FOREIGN KEY (diagram_id) REFERENCES diagrams(id) ON DELETE CASCADE;
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'diagram_members'::regclass
                  AND contype = 'f'
                  AND lower(pg_get_constraintdef(oid)) LIKE
                      'foreign key (user_id) references users(id) on delete cascade%'
            ) THEN
                ALTER TABLE diagram_members
                    ADD CONSTRAINT fk_diagram_members_user_id
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_diagram_members_diagram_id ON diagram_members (diagram_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_diagram_members_user_id ON diagram_members (user_id)")

def downgrade():
    op.drop_table("diagram_members")
