from alembic import op

revision = "0006_deployments"
down_revision = "0005_diagram_members"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        CREATE TABLE IF NOT EXISTS deployments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            diagram_id UUID NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'queued',
            slug VARCHAR(60) NOT NULL,
            container_name VARCHAR(100), db_container_name VARCHAR(100),
            image_name VARCHAR(100), url VARCHAR(255),
            error_summary VARCHAR(500), project_hash VARCHAR(64),
            project_json TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS diagram_id UUID")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'queued'")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS slug VARCHAR(60)")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS container_name VARCHAR(100)")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS db_container_name VARCHAR(100)")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS image_name VARCHAR(100)")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS url VARCHAR(255)")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS error_summary VARCHAR(500)")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS project_hash VARCHAR(64)")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS project_json TEXT")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    op.execute("ALTER TABLE deployments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    op.execute("UPDATE deployments SET status = 'queued' WHERE status IS NULL")
    op.execute("UPDATE deployments SET project_json = '{}' WHERE project_json IS NULL")
    op.execute("UPDATE deployments SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE deployments SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")
    op.execute("ALTER TABLE deployments ALTER COLUMN status SET DEFAULT 'queued'")
    op.execute("ALTER TABLE deployments ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP")
    op.execute("ALTER TABLE deployments ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP")
    op.execute("ALTER TABLE deployments ALTER COLUMN diagram_id SET NOT NULL")
    op.execute("ALTER TABLE deployments ALTER COLUMN status SET NOT NULL")
    op.execute("ALTER TABLE deployments ALTER COLUMN slug SET NOT NULL")
    op.execute("ALTER TABLE deployments ALTER COLUMN project_json SET NOT NULL")
    op.execute("ALTER TABLE deployments ALTER COLUMN created_at SET NOT NULL")
    op.execute("ALTER TABLE deployments ALTER COLUMN updated_at SET NOT NULL")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'deployments'::regclass AND conname = 'deployments_pkey') THEN
                ALTER TABLE deployments ADD CONSTRAINT deployments_pkey PRIMARY KEY (id);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'deployments'::regclass AND conname = 'uq_deployment_diagram') THEN
                ALTER TABLE deployments ADD CONSTRAINT uq_deployment_diagram UNIQUE (diagram_id);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'deployments'::regclass AND conname = 'ck_deployment_status') THEN
                ALTER TABLE deployments ADD CONSTRAINT ck_deployment_status
                    CHECK (status IN ('queued','building','starting','running','failed','stopped'));
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conrelid = 'deployments'::regclass AND contype = 'f'
                  AND lower(pg_get_constraintdef(oid)) LIKE
                      'foreign key (diagram_id) references diagrams(id) on delete cascade%'
            ) THEN
                ALTER TABLE deployments ADD CONSTRAINT fk_deployments_diagram_id
                    FOREIGN KEY (diagram_id) REFERENCES diagrams(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)


def downgrade():
    op.drop_table("deployments")
