import { useCallback, useEffect, useRef, useState } from "react";
import { json, request } from "../api.js";
import { Inspector, AssistantLauncher, AssistantPanel, DeploymentPanel, MembersPanel, RelationInspector, RelationModal, Sidebar, SqlEditor, TopBar } from "../components/index.jsx";
import { ClassCard } from "../features/canvas/ClassCard.jsx";
import { CollaboratorCursor } from "../features/canvas/CollaboratorCursor.jsx";
import { ZoomControls } from "../features/canvas/ZoomControls.jsx";
import { useCanvasCollaboration } from "../features/canvas/useCanvasCollaboration.js";
import { useCanvasGestures } from "../features/canvas/useCanvasGestures.js";
import { RelationLayer } from "../features/canvas/RelationLayer.jsx";
import { relationContext } from "../relation-context.js";
import { MIN_ZOOM, MAX_ZOOM, ZOOM_STEP, zoomedCanvasPoint, zoomPercent } from "../canvas-geometry.js";
import { normalizeDiagram as diagramData } from "../lib/diagram-normalizers.js";

export const canvasPoint = zoomedCanvasPoint;

function BoardCanvas({ id, onBack, onLogout, currentUser, theme, onThemeToggle, initialSqlOpen = false }) {
  const [diagram, setDiagram] = useState(null), [members, setMembers] = useState([]), [membersOpen, setMembersOpen] = useState(false), [inspectorOpen, setInspectorOpen] = useState(true), [classDimensions, setClassDimensions] = useState({}), [selectedClassId, setSelectedClassId] = useState(null), [selectedRelationId, setSelectedRelationId] = useState(null), [hoveredRelationId, setHoveredRelationId] = useState(null), [sqlOpen, setSqlOpen] = useState(initialSqlOpen), [sqlDrawerMode, setSqlDrawerMode] = useState("partial"), [relationSource, setRelationSource] = useState(null), [deploymentOpen, setDeploymentOpen] = useState(false), [assistantOpen, setAssistantOpen] = useState(false), [xmiPreview, setXmiPreview] = useState(null), [xmiBusy, setXmiBusy] = useState(false), [error, setError] = useState(""), [warning, setWarning] = useState("");
  const mutationQueue = useRef(Promise.resolve()), pendingMutations = useRef(0), refreshSequence = useRef(0), canvasRef = useRef(null), assistantLauncherRef = useRef(null), xmiInputRef = useRef(null), xmiTriggerRef = useRef(null), zoomRef = useRef(1), panRef = useRef({ x: 0, y: 0 });
  const owner = members.some((member) => member.id === currentUser.id && member.is_owner);
  const readOnly = !owner && members.find((member) => member.id === currentUser.id)?.role !== "editor";
  const updateClassDimensions = useCallback((classId, dimensions) => setClassDimensions((current) => current[classId]?.width === dimensions.width && current[classId]?.height === dimensions.height ? current : { ...current, [classId]: dimensions }), []);
  const applyDiagram = useCallback((next) => { const safeDiagram = diagramData(next); setDiagram(safeDiagram); setSelectedClassId((current) => safeDiagram.classes.some((c) => c.id === current) ? current : null); setSelectedRelationId((current) => safeDiagram.relations.some((r) => r.id === current) ? current : null); setHoveredRelationId((current) => safeDiagram.relations.some((r) => r.id === current) ? current : null); }, []);
  const refresh = useCallback(async () => { const sequence = ++refreshSequence.current, next = await request(`/diagrams/${id}`); if (sequence === refreshSequence.current) applyDiagram(next); return diagramData(next); }, [applyDiagram, id]);
  const mutate = useCallback((operation) => { pendingMutations.current += 1; const run = mutationQueue.current.catch(() => {}).then(operation).then(refresh).finally(() => { pendingMutations.current -= 1; }); mutationQueue.current = run.catch(() => {}); return run; }, [refresh]);
  useEffect(() => { request(`/diagrams/${id}`).then(applyDiagram).catch((e) => setError(e.message)); request(`/diagrams/${id}/members`).then(setMembers).catch((e) => setError(e.message)); }, [applyDiagram, id]);
  useEffect(() => { const applied = (event) => applyDiagram(event.detail); addEventListener("uml:sql-applied", applied); return () => removeEventListener("uml:sql-applied", applied); }, [applyDiagram]);
  useEffect(() => { if (!xmiPreview) return undefined; const close = (event) => { if (event.key === "Escape" && !xmiBusy) { setXmiPreview(null); requestAnimationFrame(() => xmiTriggerRef.current?.focus()); } }; addEventListener("keydown", close); return () => removeEventListener("keydown", close); }, [xmiPreview, xmiBusy]);
  const collaboration = useCanvasCollaboration({ id, currentUser, canvasRef, readOnly, refresh, mutate, pendingMutations, setError, zoomRef, panRef });
  const gestures = useCanvasGestures({ id, canvasRef, cancelClassDrag: collaboration.cancelClassDrag, zoomRef, panRef });
  if (!diagram) return <main className="loading">{error || "Cargando la pizarra..."}</main>;
  const renderedDiagram = { ...diagram, classes: diagram.classes.map((item) => collaboration.visualPositions[item.id] ? { ...item, ...collaboration.visualPositions[item.id] } : item) };
  const selected = renderedDiagram.classes.find((c) => c.id === selectedClassId) || null, selectedRelation = renderedDiagram.relations.find((r) => r.id === selectedRelationId) || null;
  const addClass = async () => mutate(() => request(`/diagrams/${id}/classes`, json("POST", { name: "NuevaClase", x: 100 + diagram.classes.length * 240, y: 100 })));
  const validClassId = (classId) => { if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(classId || "")) throw Error("El identificador de clase no es válido. Actualice el diagrama e intente nuevamente."); return classId; };
  const patchClass = async (patch) => { if (!selectedClassId) return; validClassId(selectedClassId); const safePatch = { ...patch }; if ("x" in safePatch) safePatch.x = Math.max(0, Math.round(Number(safePatch.x))); if ("y" in safePatch) safePatch.y = Math.max(0, Math.round(Number(safePatch.y))); return mutate(() => request(`/classes/${selectedClassId}`, json("PATCH", safePatch))); };
  const deleteClass = async () => { if (!selectedClassId) return; await mutate(() => request(`/classes/${selectedClassId}`, { method: "DELETE" })); setSelectedClassId(null); };
  const addItem = async (kind) => { if (selectedClassId) await mutate(() => request(`/classes/${selectedClassId}/${kind}`, json("POST", { name: kind === "attributes" ? "campo" : "ejecutar", type: kind === "attributes" ? "string" : "void" }))); };
  const patchItem = (kind, item, patch) => mutate(() => request(`/details/${kind}/${item}`, json("PATCH", patch)));
  const deleteItem = (kind, item) => mutate(() => request(`/details/${kind}/${item}`, { method: "DELETE" }));
  const patchRelation = (patch) => selectedRelationId && mutate(() => request(`/relations/${selectedRelationId}`, json("PATCH", patch)));
  const deleteRelation = async () => { if (selectedRelationId) await mutate(() => request(`/relations/${selectedRelationId}`, { method: "DELETE" })); setSelectedRelationId(null); };
  const createRelation = async (payload) => { await mutate(() => request(`/diagrams/${id}/relations`, json("POST", payload))); setRelationSource(null); };
  const exportBoard = async () => { const blob = await request(`/diagrams/${id}/export`, { method: "POST" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `uml-${id}.zip`; a.click(); URL.revokeObjectURL(a.href); };
  const exportXmi = async () => { try { const blob = await request(`/diagrams/${id}/xmi`); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `uml-${id}.xmi`; a.click(); URL.revokeObjectURL(a.href); } catch (e) { setError(e.message); } };
  const chooseXmi = () => { setError(""); setWarning(""); xmiTriggerRef.current = document.activeElement; xmiInputRef.current?.click(); };
  const validateXmi = async (event) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setXmiBusy(true); setError(""); setWarning(""); try { const form = new FormData(); form.append("file", file); const preview = await request(`/diagrams/${id}/xmi/validate`, { method: "POST", body: form }); setXmiPreview({ file, ...preview }); } catch (e) { setError(e.message); } finally { setXmiBusy(false); } };
  const confirmXmi = async () => { if (!xmiPreview?.file) return; setXmiBusy(true); setError(""); setWarning(""); try { const form = new FormData(); form.append("file", xmiPreview.file); form.append("confirm", "true"); const result = await request(`/diagrams/${id}/xmi/import`, { method: "POST", body: form }); setXmiPreview(null); await refresh(); setSelectedClassId(null); setSelectedRelationId(null); setHoveredRelationId(null); if (xmiTriggerRef.current?.focus) requestAnimationFrame(() => xmiTriggerRef.current.focus()); if (result.warnings?.length) setWarning(result.warnings.join(" ")); } catch (e) { setError(e.message); } finally { setXmiBusy(false); } };
  const hoverContext = hoveredRelationId && typeof hoveredRelationId === "object" ? hoveredRelationId : null, hoveredId = hoverContext?.relationId || null, activeRelationContext = hoverContext || relationContext(selectedRelation);
  const stageWidth = Math.max(2400, ...renderedDiagram.classes.map((item) => Number(item.x) + 260)), stageHeight = Math.max(1600, ...renderedDiagram.classes.map((item) => Number(item.y) + 500));
  return <div className="app-shell editor"><Sidebar currentUser={currentUser} onLogout={onLogout} /><div className="app-content"><TopBar title={diagram.title} onBack={onBack} currentUser={currentUser} onExport={owner ? exportBoard : null} onExportXmi={exportXmi} onImportXmi={readOnly ? null : chooseXmi} onDeploy={owner ? () => setDeploymentOpen(true) : null} onAddClass={readOnly ? null : addClass} onMembers={owner ? () => setMembersOpen(true) : null} onSql={() => { setSqlOpen((open) => !open); if (!sqlOpen) setSqlDrawerMode("partial"); }} sqlOpen={sqlOpen} theme={theme} onThemeToggle={onThemeToggle} />
     <input ref={xmiInputRef} className="sr-only" type="file" accept=".xmi,.xml,application/xml,text/xml" onChange={validateXmi} />
     {xmiBusy && <p className="xmi-status" role="status">Procesando XMI...</p>}
     {xmiPreview && <div className="modal-backdrop"><section className="relation-modal xmi-preview" role="dialog" aria-modal="true" aria-labelledby="xmi-preview-title"><h2 id="xmi-preview-title">Vista previa de importación XMI</h2><p className="muted">{xmiPreview.file.name}</p><p>{xmiPreview.summary.classes} clases · {xmiPreview.summary.attributes} atributos · {xmiPreview.summary.methods} métodos · {xmiPreview.summary.relations} relaciones</p>{xmiPreview.warnings?.length ? <div className="xmi-warnings"><strong>Advertencias</strong><ul>{xmiPreview.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div> : <p className="notice">No se detectaron advertencias.</p>}<p className="muted">La importación reemplazará el contenido actual de esta pizarra.</p><div className="form-actions"><button onClick={confirmXmi} disabled={xmiBusy}>Confirmar reemplazo</button><button className="ghost" onClick={() => { setXmiPreview(null); requestAnimationFrame(() => xmiTriggerRef.current?.focus()); }} disabled={xmiBusy}>Cancelar</button></div></section></div>}
     {error && <p className="error editor-error">{error}</p>}{warning && <aside className="import-warning" role="status"><strong>Importación completada con información</strong><span>El contenido compatible se conservó. {warning}</span><button type="button" className="ghost" onClick={() => setWarning("")}>Ocultar</button></aside>}<main className={`workspace ${inspectorOpen ? "inspector-open" : ""}`}><section ref={canvasRef} className={`canvas ${gestures.isPanning ? "is-panning" : ""}`} onPointerDown={gestures.startPan} onPointerMove={(event) => { gestures.movePan(event); collaboration.sendCursor(event); }} onPointerUp={gestures.endPan} onPointerCancel={gestures.endPan} onLostPointerCapture={gestures.endPan} onContextMenu={(event) => event.preventDefault()} onWheel={gestures.handleWheel}><div className="zoom-controls" aria-label="Controles de zoom"><ZoomControls zoom={gestures.zoom} minZoom={MIN_ZOOM} maxZoom={MAX_ZOOM} zoomStep={ZOOM_STEP} zoomPercent={zoomPercent} onZoom={(next) => gestures.changeZoom(next)} /></div>
      {!readOnly && <div className="assistant-overlay">{!assistantOpen && <AssistantLauncher launcherRef={assistantLauncherRef} onOpen={() => setAssistantOpen(true)} />}{assistantOpen && <AssistantPanel diagramId={id} onClose={() => { setAssistantOpen(false); requestAnimationFrame(() => assistantLauncherRef.current?.querySelector("button")?.focus()); }} onChanged={refresh} />}</div>}
      <div className="canvas-stage" style={{ width: stageWidth, height: stageHeight, transform: `translate3d(${gestures.pan.x}px, ${gestures.pan.y}px, 0) scale(${gestures.zoom})` }}><RelationLayer diagram={renderedDiagram} classDimensions={classDimensions} selectedId={selectedRelationId} hoveredId={hoveredId} onSelect={(rid) => { setInspectorOpen(true); setSelectedRelationId(rid); setSelectedClassId(null); }} onHover={setHoveredRelationId} />{Object.values(collaboration.remoteCursors).map((cursor) => <CollaboratorCursor key={cursor.userId} cursor={cursor} />)}{renderedDiagram.classes.map((item) => <ClassCard key={item.id} item={item} readOnly={readOnly} relationContext={activeRelationContext} onSelect={(cid) => { setInspectorOpen(true); setSelectedClassId(cid); setSelectedRelationId(null); }} onRelation={setRelationSource} onDrag={collaboration.drag} onResize={updateClassDimensions} />)}</div>
    </section>{inspectorOpen && (selectedRelation ? <RelationInspector readOnly={readOnly} relation={selectedRelation} diagram={renderedDiagram} onPatch={patchRelation} onDelete={deleteRelation} onClose={() => { setInspectorOpen(false); setSelectedRelationId(null); }} /> : <Inspector readOnly={readOnly} selected={selected} onPatch={patchClass} onDelete={deleteClass} onAdd={addItem} onItemPatch={patchItem} onItemDelete={deleteItem} onClose={() => { setInspectorOpen(false); setSelectedClassId(null); }} />)}</main>
    {sqlOpen && <SqlEditor diagramId={id} diagramTitle={diagram.title} readOnly={readOnly} currentUserId={currentUser.id} drawerMode={sqlDrawerMode} onDrawerModeChange={setSqlDrawerMode} onApplied={applyDiagram} />}{relationSource && !readOnly && <RelationModal classes={renderedDiagram.classes} initialSource={relationSource} onCancel={() => setRelationSource(null)} onCreate={createRelation} />}{membersOpen && <MembersPanel diagramId={id} onClose={() => { setMembersOpen(false); request(`/diagrams/${id}/members`).then(setMembers); }} />}{deploymentOpen && <DeploymentPanel diagramId={id} onClose={() => setDeploymentOpen(false)} />}</div></div>;
}

export function BoardEditor(props) { return <BoardCanvas {...props} />; }
export function SqlWorkspace({ id, onBack, onLogout, currentUser, theme, onThemeToggle }) { return <BoardCanvas id={id} onBack={onBack} onLogout={onLogout} currentUser={currentUser} theme={theme} onThemeToggle={onThemeToggle} initialSqlOpen />; }
